### ISSUE TITLE
"Cannot find rendered stateless component" error when upgrading to React v16

### ISSUE THREAD

**Issue by ezmiller** [bruderstein/unexpected-react#50] opened 2017-11-09 17:25 UTC
I'm upgrading to React v16 and have hit some snags with my unexpected-react tests. In some cases, it seems that the deep rendering mechanism isn't working quite right. For examle the following test, gives an error:

```
    expect(
      <Toc
        nodes={singleLevelTocData}
        {...Object.assign({ openPaths: {}, carUuid: mockedData.uuid }, props)}
      />,
      'when deeply rendered', 'to have rendered',
      <ul>
        <li data-stripe={1}>
          <a className="has-children">
            <span className="label">
              <span className="label-node">Body</span>
            </span>
          </a>
        </li>
        <li data-stripe={0}>
          <a className="has-children">
            <span className="label">
              <span className="label-node">Chassis</span>
            </span>
          </a>
        </li>
        <li data-stripe={1}>
          <a className="has-children">
            <span className="label">
              <span className="label-node">Powertrain</span>
            </span>
          </a>
        </li>
      </ul>
    );
```

From the error output it seems clear that the test isn't see the resulting DOM elements. It seems only to see the components. The resulting error notes on the bottom that it "cannot find rendered stateless component":

```
     UnexpectedError:
expected
<Toc
   nodes={[
  { title: 'Body', count: 16, path: '/ssc/body', dot_path: '0.0', children: ... },
  { title: 'Chassis', count: 13, path: '/ssc/chassis', dot_path: '0.1', children: ... },
  { title: 'Powertrain', count: 88, path: '/ssc/powertrain', dot_path: '0.2', children: ... }
]}
   openPaths={{}} carUuid="294189a029390ebc444b367884a9474a"
   route="tocSearchPath" itemsBefore={0} handleClick={function handleClick() {}}
   generateNodeHref={function generateNodeHref() {}} highlightUuid=""
/>
when deeply rendered
to have rendered <ul>
  <li data-stripe={1}>
    <a className="has-children">
      <span className="label"><span className="label-node">Body</span></span>
    </a>
  </li>
  <li data-stripe={0}>
    <a className="has-children">
      <span className="label"><span className="label-node">Chassis</span></span>
    </a>
  </li>
  <li data-stripe={1}>
    <a className="has-children">
      <span className="label"><span className="label-node">Powertrain</span></span>
    </a>
  </li>
</ul>
  Cannot find rendered stateless component. Are you sure you passed a real component to `when deeply rendered`
```
Any idea what might be going on here? In prepping for v16, I noted the advice in the README to use jsdom-global, so my `emulateDom` file now looks like:

```
require('jsdom-global')();
require('./requestAnimationFramePolyfill');
```
where requestAnimationFramePolyfill.js is the polyfill linked in the README: https://gist.github.com/paulirish/1579671

**Comment by bruderstein** [comment] 2017-11-09 17:35
I take it `Toc` is a stateless component? It'd be very, interesting to know what happens if you made it a stateful class component.

Other than that, I presume you're on v5 of unexpected-react? What version of node?

**Comment by ezmiller** [comment] 2017-11-09 19:00
@bruderstein: I converted it to a class component to see what would happen. The message regarding the stateless component disappeared, but it still isn't seeing the rendered DOM elements. I am indeed on v5 of unexpected-react. Node v6.9.4.

**Comment by bruderstein** [comment] 2017-11-10 09:05
Is there any message (try with `UNEXPECTED_FULL_TRACE=1` set as an environment variable)? 

Is it just this component, or do all components exhibit this behaviour? 

If possible, just to confirm, can you clear your `node_modules` and reinstall, i wonder if there's an old version of something in there.

I'll try it on that version of node tonight, just in case.  I'll also try and get some more precise instructions so we can work out where it's failing.

**Comment by bruderstein** [comment] 2017-11-12 10:55
I ran the test suite on node 6.9.4, and that all worked, so i don't think it's that.

I highly suspect it's something in your node_modules (like two copies of react or react-render-hook library, for example).  Clearing it and doing a reinstall should fix that. 

If it doesn't, can you try adding a `const hooks = require('react-render-hook');` as the first line of your test file, and then doing the following (passing the same props as before to `Toc`):
```
const component = ReactDOM.render(<Toc ... />, document.createElement('div'));
console.log(hooks.findComponent(component);
```

Use the class version of `<Toc>`.  As long as that console.log dumps out a bunch of data, then the fundamentals are working, and the issue is probably some duplication of packages somewhere, if it doesn't, something is very odd. I'd be keen to know in that case the exact versions of your deps (specifically react, react-dom & react-test-renderer)

**Comment by bruderstein** [comment] 2018-11-04 11:54
Closing this as no feedback and it isn't reproducible

**Closed by bruderstein** 2018-11-04 11:54 UTC
